### ISSUE TITLE
How do I add a SEEN flag to the message in gmail ?

### ISSUE THREAD

**Issue by qharlie** [mscdex/node-imap#124]
I've tried 

imap.addFlags(msg.uid, '\SEEN');
imap.addFlags(msg.uid, 'SEEN');
imap.addFlags(msg.uid, '(SEEN)');

All get the same response : 

Error: The flag "\SEEN" is not allowed by the server for this mailbox
    at ImapConnection._store (/home/q/workspace/formhog/node_modules/imap/lib/imap.js:1164:15)
    at ImapConnection.addFlags (/home/q/workspace/formhog/node_modules/imap/lib/imap.js:958:8)
    at ImapMessage.<anonymous> (/home/q/workspace/formhog/server/scratch.js:90:22)
    at ImapMessage.EventEmitter.emit (events.js:85:17)
    at CleartextStream.ondata (/home/q/workspace/formhog/node_modules/imap/lib/imap.js:284:19)
    at CleartextStream.EventEmitter.emit (events.js:88:17)
    at CleartextStream.CryptoStream._push (tls.js:491:12)
    at SecurePair.cycle (tls.js:849:20)
    at EncryptedStream.CryptoStream.write (tls.js:230:13)
    at Socket.ondata (stream.js:38:26)

**Comment by nsubhadipta** [comment]
**Read To UnRead in IMAP FLOW Code**

    client.messageFlagsAdd({uid: 116,seen: false}, ['\\Seen']);

    client.messageFlagsRemove({uid: 116,seen: true}, ['\\Seen']);
