### ISSUE TITLE
Error "Hostname/IP doesn't match certificate's altnames" with Node 0.10.0

### ISSUE THREAD

**Issue by naholyr** [mscdex/node-imap#181]
Hello,

I cannot find any way to connect to `imap.gmail.com` anymore when using `imap` with Node 0.10.0, it continuously throws the following error:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Hostname/IP doesn't match certificate's altnames
    at SecurePair.<anonymous> (tls.js:1280:23)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:883:10)
    at CleartextStream.read [as _read] (tls.js:421:15)
    at CleartextStream.Readable.read (_stream_readable.js:293:10)
    at EncryptedStream.write [as _write] (tls.js:330:25)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at EncryptedStream.Writable.write (_stream_writable.js:172:11)
    at write (_stream_readable.js:547:24)
```

I'm not sure exactly why this happens, in previous versions it happened when you provided a direct IP for connection, but it's not the case here.

I'll try to dig further, but for the moment I have no idea :s

Note: i tested with all available 0.9.x versions and I can say it's still working in 0.9.1, and starts failing at 0.9.2.

**Comment by scottie** [comment]
imap.connect({rejectUnauthorized: false}); ??

**Comment by maxnaude** [comment]
Usage example:

```
let imap = new Imap({
  ...
  tlsOptions: {
    rejectUnauthorized: false,
  }
});
```
