### ISSUE TITLE
Question regarding bodies

### ISSUE THREAD

**Issue by alessioalex** [mscdex/node-imap#369]
Hey, can somebody please help me out translating this into the `bodies` param please?

``` bash
(UID FLAGS) (CHANGEDSINCE 2277561)
```

This doesn't work ('could not parse command'):

``` js
var f = imap.seq.fetch(from + ':' + to, {
  bodies: '(UID FLAGS) (CHANGEDSINCE 2277561)',
  struct: true
});
```

Thanks!

**Comment by delsner** [comment]
Could you maybe explain more deeply how you have exactly solved the issue? I'm facing the same issue and what I want to do is keep my gmail imap in sync with my node-server. What I'm currently trying to do when I sync is this: 

```
this.imap.seq.fetch('1:*', {
          bodies: '',
          struct: true,
          markSeen: false,
          extensions: ['X-GM-LABELS'],
          modifiers: {
            changedsince: this.options.currentUser.highestmodseq || '0'
          },
        }
```

That way I'm trying to only fetch those emails that have changed. Is that the correct approach?

**Comment by mscdex** [comment]
@delsner AFAIK that should work, are you having problems with that or ?

**Comment by delsner** [comment]
@mscdex I have problems with that. Maybe I have to be more precise how I'm using this (great!) library. I have a (unfortunately!) stateless node-server which serves as the backend to an email-client through a REST API. 

Now when the user hits the sync button I want to sync all the boxes and update only those emails that have been touched since the last sync - therefore, I wanted to make use of the CONDSTORE IMAP-Extension by using _changessince_. 

What I'm doing is I create one imap-connector ( new Imap()...) and then sequentially fetch all boxes (from my previous experiences with node-imap it doesn't support multiple async calls at once):

**Controller:**
```
  Promise.each(req.body.boxes, (box) => {
    return imapConnector.fetchEmails(box.name);
  }).then(() => {console.log('Finished fetching'});
```

**ImapConnector:**
```
fetchEmails(boxName) {
    return this.openBoxAsync(boxName).then((box) => {
        return this.imap.getMailAsync(this.imap.seq.fetch('1:*', {
          bodies: '',
          struct: true,
          markSeen: false,
          extensions: ['X-GM-LABELS'],
          modifiers: {
            changedsince: this.options.currentUser.highestmodseq || '0'
          },
        }), (mail) => {
          if (box && box.highestmodseq) {
            this.options.currentUser.highestmodseq = box.highestmodseq;
            this.options.currentUser.save();
          }
          return this.parseDataFromEmail(mail, boxName);
        });
      })
      .then((messages) => {
        return messages;
      })
      .catch((error) => {
        console.error('Error: ', error.message);
      });
  }
```

I use a simple promise wrapper as described here: https://github.com/bitdivine/node-imap-promise/blob/master/ImapPromise.js . But this shouldn't influence the workflow I believe, what do you think?

**Comment by mscdex** [comment]
@delsner I don't know anything about the Promise-wrapping module. As far as "async calls" go, the `imap` module uses a queue, so there is only one request executing at any given time. That means you *should* be able to just queue up as many requests as you want. IMAP (the protocol) does not really do async very well. It's kind of supported in some cases but there are caveats, so to avoid any of those issues this module just uses a queue.

I'm still not sure what issue you're attempting to describe is? Are you getting an error? An exception being thrown? Or is the code working but you're just asking for some kind of advice? Or something else?

**Comment by delsner** [comment]
@mscdex It's good to know, that you can queue up requests, thanks. Sorry, that I wasn't clear enough: The code itself doesn't throw any errors, however, the mechanism is not working. The fetchEmails() function always fetches all emails, not only the ones that have changed since the _highestmodseq_ . But if you don't see any mistakes in the way I approach the functionality of the IMAP-Extension then it's probably a implementation fault in my logic. That already helps me :)

**Comment by mscdex** [comment]
@delsner Did you check that the `.highestmodseq` you have stored is set to a non-empty string? If it is, can you set `debug: console.log` in the connection config and check (in the resulting debug output) that the request sent by `fetch()` to ensure that the `.highestmodseq` value is sent (and that it matches the modseq value shown when opening the mailbox)?

**Comment by delsner** [comment]
yeah it's not empty and it's send by the fetch() as well:
e.g.
```
[connection] Connected to host
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- APPENDLIMIT=35651584'
<= 'A1 OK x@gmail.com authenticated (Success)'
=> 'A2 NAMESPACE'
<= '* NAMESPACE (("" "/")) NIL NIL'
<= 'A2 OK Success'
=> 'A3 LIST "" ""'
<= '* LIST (\\Noselect) "/" "/"'
<= 'A3 OK Success'
=> 'IDLE IDLE'
<= '+ idling'
=> DONE
<= 'IDLE OK IDLE terminated (Success)'
=> 'A4 SELECT "INBOX" (CONDSTORE)'
<= '* FLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $NotPhishing $Phishing)'
<= '* OK [PERMANENTFLAGS (\\Answered \\Flagged \\Draft \\Deleted \\Seen $NotPhishing $Phishing \\*)] Flags permitted.'
<= '* OK [UIDVALIDITY 1] UIDs valid.'
<= '* 16 EXISTS'
<= '* 0 RECENT'
<= '* OK [UIDNEXT 164] Predicted next UID.'
<= '* OK [HIGHESTMODSEQ 26215]'
<= 'A4 OK [READ-WRITE] INBOX selected. (Success)'
=> 'IDLE IDLE'
<= '+ idling'
=> DONE
<= 'IDLE OK IDLE terminated (Success)'
=> 'A5 FETCH 1:* (X-GM-THRID X-GM-MSGID X-GM-LABELS MODSEQ UID FLAGS INTERNALDATE BODYSTRUCTURE X-GM-LABELS BODY.PEEK[]) (CHANGEDSINCE 26019)'
<= '* 3 FETCH (X-GM-THRID 1552072915674217519 X-GM-MSGID 1552072915674217519 X-GM-LABELS ("\\\\Important") X-GM-LABELS ("\\\\Important") UID 86 MODSEQ (26025) INTERNALDATE "26-Nov-2016 14:54:36 +0000" FLAGS (\\Seen) BODYSTRUCTURE ("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 424 9 NIL NIL NIL) BODY[] {2113}'
<= '* 3 FETCH (X-GM-THRID 1552072915674217519 X-GM-MSGID 1552072915674217519 X-GM-LABELS ("\\\\Important") X-GM-LABELS ("\\\\Important") UID 86 MODSEQ (26025) INTERNALDATE "26-Nov-2016 14:54:36 +0000" FLAGS (\\Seen) BODYSTRUCTURE ("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL "7BIT" 424 9 NIL NIL NIL) )'
<= '* 12 FETCH (X-GM-THRID 1556136739025124575 X-GM-MSGID 1556136739025124575 X-GM-LABELS () X-GM-LABELS () UID 156 MODSEQ (26198) INTERNALDATE "10-Jan-2017 11:27:20 +0000" FLAGS (\\Seen) BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 597 18 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 25238 636 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "----sinikael-?=_1-14840476404950.23768100250220492") NIL NIL) BODY[] {28263}'
<= '* 12 FETCH (X-GM-THRID 1556136739025124575 X-GM-MSGID 1556136739025124575 X-GM-LABELS () X-GM-LABELS () UID 156 MODSEQ (26198) INTERNALDATE "10-Jan-2017 11:27:20 +0000" FLAGS (\\Seen) BODYSTRUCTURE (("TEXT" "PLAIN" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 597 18 NIL NIL NIL)("TEXT" "HTML" ("CHARSET" "utf-8") NIL NIL "QUOTED-PRINTABLE" 25238 636 NIL NIL NIL) "ALTERNATIVE" ("BOUNDARY" "----sinikael-?=_1-14840476404950.23768100250220492") NIL NIL) )'
<= '* 16 FETCH (X-GM-THRID 1557336791911223481 X-GM-MSGID 1557336791911223481 X-GM-LABELS ("\\\\Important" "\\\\Sent") X-GM-LABELS ("\\\\Important" "\\\\Sent") UID 163 MODSEQ (26163) INTERNALDATE "23-Jan-2017 17:21:40 +0000" FLAGS () BODYSTRUCTURE ("TEXT" "PLAIN" NIL NIL NIL "7BIT" 0 0 NIL NIL NIL) BODY[] {622}'
<= '* 16 FETCH (X-GM-THRID 1557336791911223481 X-GM-MSGID 1557336791911223481 X-GM-LABELS ("\\\\Important" "\\\\Sent") X-GM-LABELS ("\\\\Important" "\\\\Sent") UID 163 MODSEQ (26163) INTERNALDATE "23-Jan-2017 17:21:40 +0000" FLAGS () BODYSTRUCTURE ("TEXT" "PLAIN" NIL NIL NIL "7BIT" 0 0 NIL NIL NIL) )'
<= 'A5 OK Success'
=> 'IDLE IDLE'
<= '+ idling'
TypeError: Cannot read property 'type' of undefined
    at Parser.<anonymous> (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Connection.js:226:28)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resContinue (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:296:8)
    at Parser._parse (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:141:16)
    at Parser._tryread (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:438:10)
    at emitReadable (_stream_readable.js:432:7)
    at readableAddChunk (_stream_readable.js:183:13)
    at TLSSocket.Readable.push (_stream_readable.js:130:10)
    at TLSWrap.onread (net.js:542:20)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

**Comment by mscdex** [comment]
As far as the fetch responses go, they all look legit to me -- the modseq numbers are all higher than the changedsince value. If you use `'26215'` for the changedsince, you should get no results, correct?

Regarding the error, yes, that should not be happening. What version of `imap` are you using?

**Comment by delsner** [comment]
I'm using 0.8.19. Do you want me to open an issue for it? I couldn't find one for this error neither for the other one that I'm getting when I'm trying to add/delete flags:

```
<= '* 3 FETCH (UID 4 MODSEQ (26109) FLAGS (\\Seen))'
TypeError: Cannot read property 'fullcmd' of undefined
    at ImapPromises.Connection._resUntagged (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Connection.js:1403:44)
    at Parser.<anonymous> (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Connection.js:190:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resUntagged (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:271:10)
    at Parser._parse (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:137:16)
    at Parser._tryread (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/Users/delsner/workspace/email-client/emailappserver/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:438:10)
    at emitReadable (_stream_readable.js:432:7)
    at readableAddChunk (_stream_readable.js:183:13)
    at TLSSocket.Readable.push (_stream_readable.js:130:10)
    at TLSWrap.onread (net.js:542:20)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

```

**Comment by mscdex** [comment]
@delsner Yes, open a new issue please.

**Comment by delsner** [comment]
@mscdex I've created two issues for those errors. One general question, do you think it is a problem that I open and end an IMAP connection on every request? As you see have disabled the *keepAlive* option...
