### ISSUE TITLE
STORE attempt on READ-ONLY folder error when I try to add a delete flag

### ISSUE THREAD

**Issue by christiaanwesterbeek** [mscdex/node-imap#408]
When I do this (with uid=6):

``` javascript
imap.addFlags(uid, 'Deleted', function(err) {
  if (err)  throw err;
  console.log('Email archived');
});
```

I get this response that I did not expect.

```
Error: STORE attempt on READ-ONLY folder (Failure)
    at Connection._resTagged (D:\programs\node-imap\node_modules\imap\lib\Connection.js:1451:11)
    at Parser.<anonymous> (D:\programs\node-imap\node_modules\imap\lib\Connection.js:173:10)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser._resTagged (D:\programs\node-imap\node_modules\imap\lib\Parser.js:174:10)
    at Parser._parse (D:\programs\node-imap\node_modules\imap\lib\Parser.js:138:16)
    at Parser._tryread (D:\programs\node-imap\node_modules\imap\lib\Parser.js:82:15)
    at CleartextStream.Parser._cbReadable (D:\programs\node-imap\node_modules\imap\lib\Parser.js:53:12)
    at CleartextStream.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at _stream_readable.js:401:7
```

Can't really address this error. Can you help me out?

The uid is one of the few I got from an earlier fetch

``` javascript
var f = imap.seq.fetch('1:3', {
  bodies: ['HEADER.FIELDS (FROM SUBJECT DATE)'],
  struct: true
});
```

**Comment by naho2081** [comment]
It seems that is current node-imap version second argument must be set to ```false``` in order to be able perform Write operations (mark as Read, Delete etc.)
