### ISSUE TITLE
Unhandled error ECONNREFUSED when tls is being used

### ISSUE THREAD

**Issue by pravincar** [mscdex/node-imap#467]
This happens only when tls:true was used in the constructor.  
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)
```

**Comment by mscdex** [comment]
Did you attach an `error` event handler?

**Comment by pravincar** [comment]
Yeah. Snippet below.

```
var imap=new Imap({user:username,password:password,host:'localhost',port:9993,tls:true,tlsOptions:{rejectUnauthorized:false}});
imap.once('error', function(err) {
	console.log('imap error',err);
});
```

**Comment by mscdex** [comment]
I can only reproduce this with node v0.12.x. node v0.10 and latest iojs emit the error as expected.

It looks like a regression.

**Comment by mscdex** [comment]
[Issue filed](https://github.com/joyent/node/issues/14475).
