### ISSUE TITLE
Error: No mailbox is currently selected

### ISSUE THREAD

**Issue by kaldimar** [mscdex/node-imap#481]
I've got another hard to reproduce issue, as it happens very occasionally, like in the past day it happened 24 times out of 11,360 connections. I'll try to describe it.

Our app loops through a list of mailboxes, sequentially connecting to each, running a search and then closing the mailbox prior to connect to the next one.

On rare occasions, the script dies with the following log:
```
/mnt/task/node_modules/imap/lib/Connection.js:546
    throw new Error('No mailbox is currently selected');
          ^
Error: No mailbox is currently selected
    at Connection._search (/mnt/task/node_modules/imap/lib/Connection.js:546:11)
    at Connection.search (/mnt/task/node_modules/imap/lib/Connection.js:541:8)
```
I'm calling `imap.openBox('Inbox', false, callback)`, and inside the callback, where `box` should not be undefined, I call `imap.search()`

My far-fetched assumption may have to be with our looped design. `imap.end()` is obviously an async call, without a callback. I'm guessing maybe once in a while `socket.end()` happens while the next iteration's `imap.openBox()` already started, and by the millisecond we get to the `search()`, the socket does not exist anymore. Does that make any sense? Can you comment on this issue and help me to avoid this exception?

**Comment by mscdex** [comment]
Can you provide some simple code that shows the basics of what you're doing?

Also, if you're merely changing mailboxes, you can just keep calling `openBox()` because that will do an implicit close server-side on the previous mailbox.

**Comment by kaldimar** [comment]
I am connecting to potentially a different mailbox (i.e. Inbox, Spam, etc) on different accounts. In other words, each iteration serves a different email address. Did you mean the explicit call to `imap.end()` is superfluous and the next `new Imap().connect()` would close the previous session?

**Comment by mscdex** [comment]
Sorry, no, I thought you meant you were opening different mailboxes on the same connection. Are you reusing connection objects?

**Comment by kaldimar** [comment]
This is the schematic of our application:
```
init:
get account info
var imap = new Imap(account info)
imap.connect()
imap.on('error', errorHandling())
imap.on('ready'):
  imap.openBox():
    # somewhere around here I get the exception on rare instances
    imap.search():
      imap.fetch():
      fetch.once('end', mailboxMaintenance()):
      # some messages are moved between folders if whitelisted
    imap.end()
  # some logging here
init()
```
This runs in a loop until the script runs out of accounts to check or a max timeout is reached.

I'm not sure what do you mean by reusing connections. Our idea was `imap.connect()` -> search and stuff -> `imap.end()` and start over again. I guess I'm not reusing the connection objects, as each iteration will have a different username and potentially a different host.

Does my guessing than the `imap.end()` is being delayed sometimes by network latency issues and killing the next connection, or it's nonsense?

What other reasons may undefine `box` inside the `imap.openBox()` callback? After closing the err block in this callback I just make a few variable assignments and immediately proceed to run the `imap.search()`...

**Comment by mscdex** [comment]
Did you try moving `imap.end()` inside your `fetch`'s `end` handler? `imap.end()` will enqueue a `LOGOUT`, so if your `search()` returns results that you try to fetch, the logout may have already occurred by that point.

**Comment by kaldimar** [comment]
No, I can't call `imap.end()` in the `fetch`'s `end` handler, because if the search turns out empty, I call `imap.end()`, but if it finds whitelisted senders then it calls `imap.fetch()` and `imap.move()`, and closes after the moves.
Anyways, by now I'm pretty sure the issue is caused by my implementation and it's not a bug in the library, so I'll probably close this and keep reviewing and improving my code.
A last question: is there a downside with omitting the explicit call to `imap.end()`? I.e. by opening different connection instances to different mailboxes from the same script, running additional commands, and leaving to the IMAP server the task of closing them?

**Comment by mscdex** [comment]
You could always have `imap.end();` in both places, in the `end` handler and also in an `else` in case there are no search results. The downsides to leaving the connection open are the same for leaving any TCP connection open in general. It will unnecessarily keep a socket/file descriptor open, it will keep your process open (if your process is not meant to stay alive "forever"), it ties up resources on the server-side, etc.

**Comment by kaldimar** [comment]
> You could always have `imap.end();` in both places, in the `end` handler and also

wait, isn't the `end` event emitted after the call to `imap.end()`? How can I get to that handler before calling the latter?

**Comment by mscdex** [comment]
I meant inside `fetch`'s `end` event handler, like this:

```javascript
imap.on('ready', function() {
  imap.openBox('INBOX', function(err) {
    if (err) throw err;
    imap.search(..., function(err, results) {
      if (err) throw err;
      if (results.length === 0)
        return imap.end();
      var fetch = imap.fetch(results, ...):
      fetch.once('end', function() {
        mailboxMaintenance();
        imap.end();
      }):
    });
  });
});
```

**Comment by kaldimar** [comment]
Oh, sorry for the confusion. I will try that.
Hey Brian thanks a lot for all your help along the way. I honestly believe the error in on the side of my code. But your clarifications have been invaluable to better understand why it is happening.
