### ISSUE TITLE
node v.6.0.0

### ISSUE THREAD

**Issue by kkontosis** [mscdex/node-imap#555]
Hello mscdex,
There is an incompatibility with node-imap and the new node version. A code that used to work now throws the following error:

Uncaught Error: If encoding is specified then the first argument must be a string
at new Buffer (buffer.js:106:13)
at encode (node_modules/utf7/utf7.js:4:13)
at node_modules/utf7/utf7.js:77:39
at RegExp.[Symbol.replace] (native)
at String.replace (native)
at Object.exports.imap.encode (node_modules/utf7/utf7.js:75:36)
at Connection.openBox (node_modules/imap/lib/Connection.js:412:29)

It seems it has to do with a change in the Buffer object's constructor.

**Comment by mscdex** [comment]
This is a `utf7` module issue, see [this PR](https://github.com/kkaefer/utf7/pull/2).

**Comment by kkontosis** [comment]
Thanks, mscdex

**Comment by zivbr** [comment]
@mscdex The issue in `utf7` was fixed in version 1.0.2, can you update your dependency?
