### ISSUE TITLE
No supported authentication method(s) available. Unable to login.

### ISSUE THREAD

**Issue by houxg** [mscdex/node-imap#590]
I try the demo code but it didn't work. here is the log:
```
[connection] Connected to host
<= '* OK Gimap ready for requests from 112.97.59.253 n68mb171806893iod'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 XYZZY SASL-IR AUTH=XOAUTH2 AUTH=PLAIN AUTH=PLAIN-CLIENTTOKEN AUTH=OAUTHBEARER AUTH=XOAUTH'
<= 'A0 OK Thats all she wrote! n68mb171806893iod'
{ Error: No supported authentication method(s) available. Unable to login.
    at Connection.<anonymous> (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Connection.js:1679:15)
    at Connection._resTagged (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Connection.js:1535:22)
    at Parser.<anonymous> (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Parser.js:175:10)
    at Parser._parse (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Parser.js:139:16)
    at Parser._tryread (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (D:\workspace\Learning-JS\maileater\node_modules\imap\lib\Parser.js:53:12)
    at emitNone (events.js:86:13) source: 'authentication' }
[connection] Ended
Connection ended
[connection] Closed
```

**Comment by mscdex** [comment]
What does your connection config object look like?

**Comment by houxg** [comment]
the parameters:
```
var imap = new Imap({
    user: 'mygmail@gmail.com',
    passowrd: 'gmailpassword',
    host: 'imap.gmail.com',
    port: 993,
    tls: true,
    debug: console.log
});
```
I did nothing but only change the value of `user` and `password`

**Comment by mscdex** [comment]
You have a typo: `passowrd` should be `password`.

**Comment by houxg** [comment]
oops..sorry, it works fine
