### ISSUE TITLE
TypeError('"listener" argument must be a function');

### ISSUE THREAD

**Issue by lindehoff** [mscdex/node-imap#599]
I have use this module before and it has worked, but now when I try it on a new machine I get this error:
```
events.js:307
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at Socket.once (events.js:307:11)
    at Socket.connect (net.js:943:10)
    at Connection.connect (node_modules/imap/lib/Connection.js:286:10)
    at Object.<anonymous> (imap-test.js:60:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

I have tried with the example code from the README

**Comment by lindehoff** [comment]
This was a bug on Node 7.7.2, [nodejs/node#11762](https://github.com/nodejs/node/pull/11762) 
Should be fixed in 7.7.3
