### ISSUE TITLE
Multiple Imap Connections for Multiple Clients

### ISSUE THREAD

**Issue by jirevwe** [mscdex/node-imap#605]
Hi,

Please how do I synchronize all my mailboxes using Imap.
When I try to pull all the emails from all my mailboxes, the library crashes and I get this error.

```
/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Connection.js:203
    if (self._curReq.fetchCache.hasOwnProperty(info.seqno)) {
                               ^

TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Parser.<anonymous> (/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Connection.js:203:32)
    at emitTwo (events.js:106:13)
    at Parser.emit (events.js:191:7)
    at Parser._resUntagged (/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Parser.js:196:10)
    at Parser._parse (/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Parser.js:137:16)
    at Parser._tryread (/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/Users/Kornet-Mac-1/Documents/kornet/node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
    at Socket.ondata (_stream_wrap.js:58:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```
I think it's because I'm creating two imap connections at the same time.
But I need to have multiple connections running at the same time for different users

**Comment by mscdex** [comment]
Can you share minimal code to reproduce the issue?

**Comment by jirevwe** [comment]
Hi.
When I referenced #578.
It fixed the problem.

Thanks.
