### ISSUE TITLE
Coonection Timeout after certain time  ?

### ISSUE THREAD

**Issue by paragyelonde** [mscdex/node-imap#612]
```
`Error: connection timeout at Db.<anonymous> (D:\VibesCrm v2\node_modules\mongoose\lib\drivers\node-mongodb-
   native\connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:194:7)
    at Server.listener (D:\VibesCrm v2\node_modules\mongodb\lib\db.js:1795:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Server.<anonymous> (D:\VibesCrm v2\node_modules\mongodb\lib\server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pool.<anonymous> (D:\VibesCrm v2\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (D:\VibesCrm v2\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:272:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (D:\VibesCrm v2\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:185:10)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:188:7)
    at Socket._onTimeout (net.js:352:8)
    at ontimeout (timers.js:386:14)`
```

**Comment by mscdex** [comment]
I think you posted this on the wrong issue tracker. This is the `imap` module repo, but your error is coming from the `mongoose` module.
