### ISSUE TITLE
The specified message set is invalid 

### ISSUE THREAD

**Issue by p4t0g3n0** [mscdex/node-imap#615]
Since yesterday my node server throws this error: 
"Fetch error:  { Error: The specified message set is invalid.
    at Connection._resTagged"

Before that it was working without any troubles. I'm connecting my hotmail account.

**Comment by mscdex** [comment]
Can you post the message set you're passing to `fetch()`?

**Comment by p4t0g3n0** [comment]
var fetch = imap.seq.fetch('*', {bodies: ['HEADER.FIELDS (FROM TO SUBJECT)', 'TEXT'], struct: true });

**Comment by p4t0g3n0** [comment]
This is the output:
Fetch error:  { Error: The specified message set is invalid.
    at Connection._resTagged (	node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (	node_modules/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (	node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (	node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (	node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (	node_modules/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7) type: 'bad', textCode: undefined, source: 'protocol' }

**Comment by mscdex** [comment]
Is the mailbox empty?

**Comment by p4t0g3n0** [comment]
No, I have 115 mails.

**Comment by mscdex** [comment]
It should work fine then. You could alternately try `'1:*'` when using `imap.seq.fetch()`.

**Comment by p4t0g3n0** [comment]
Thanks
