### ISSUE TITLE
Unknow Mailbox

### ISSUE THREAD

**Issue by leonardoEbert** [mscdex/node-imap#640]
I'm having trouble accessing some IMAP extensions of Gmail, I checked the code several times but I could not solve the problem

```
Debug: internal, implementation, error
    Error: Uncaught error: Unknown Mailbox: [Gmail]/Sent Mail (Failure)
    at Connection._resTagged (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Connection.js:1502:11)
    at Parser.<anonymous> (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Parser.js:175:10)
    at Parser._parse (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Parser.js:139:16)
    at Parser._tryread (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (C:\ProjetosLeonardo\Email\Server\node_modules\imap\lib\Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
```

**Comment by mscdex** [comment]
Opening that mailbox works just fine for me when connected to gmail.

**Comment by leonardoEbert** [comment]
I'll try using another account of Gmail...

**Comment by mscdex** [comment]
What version of `imap` are you using?

**Comment by leonardoEbert** [comment]
I am using the version 0.8.19

**Comment by mscdex** [comment]
Did you try calling `getBoxes()` and verifying the mailbox names/hierarchy? I'm not sure if Google translates some of those mailbox names for other languages for example.

**Comment by leonardoEbert** [comment]
That's a possibility, i am from Brazil, and Google could be translating the mailboz names.

About the `getBoxes()`, how i use it?? I don't understand how it works (i'm a trainee programmer), could you show me a sample of how to use the `getBoxes()` function??

**Comment by mscdex** [comment]
Ok so it appears Google does translate the actual mailbox names. However they do provide special attributes that denote the mailbox type, so that you can select the correct "Sent Mail" mailbox no matter what language is being used.

Just pass a callback to `getBoxes()`:

```js
imap.getBoxes((err, boxes) => {
  // check for `err` first
  // if no error, then navigate the `boxes` object to find what you want. for example:
  if (boxes['[Gmail]'] && boxes['[Gmail]'].children) {
    const children = boxes['[Gmail]'].children;
    const sentMailName = Object.keys(children).filter((name) => {
      return (children[name].attribs.includes('\\Sent'));
    })[0];
    if (sentMailName !== undefined)
      // full mailbox path is: `[Gmail]/${sentMailName}`
  }
});
```

**Comment by leonardoEbert** [comment]
Really, Google translates the name of the boxes, I do not know how I did not realize it
