### ISSUE TITLE
Error: Encoding not recognized: 'ISO-2022-JP' (searched as: 'iso2022jp')

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#643]
Dear sir, madam,
when i use node-imap to decode an email in Japanese i got an issue like bellow. How can i fix it.

```
    at Object.getCodec (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/node_modules/iconv-lite/lib/index.js:106:23)
    at Object.getDecoder (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/node_modules/iconv-lite/lib/index.js:122:23)
    at Object.decode (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/node_modules/iconv-lite/lib/index.js:40:25)
    at convertIconvLite (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/node_modules/encoding/lib/encoding.js:91:26)
    at convert (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/node_modules/encoding/lib/encoding.js:51:22)
    at Object.decodeBase64 (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/lib/mimelib.js:257:16)
    at Object.decodeMimeWord (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/lib/mimelib.js:330:25)
    at Object.module.exports.decodeMimeWord (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mimelib/lib/mimelib.js:64:41)
    at MailParser.<anonymous> (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mailparser/lib/mailparser.js:1395:24)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at MailParser._replaceMimeWords (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mailparser/lib/mailparser.js:1394:5)
    at MailParser._processHeaderLine (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mailparser/lib/mailparser.js:548:53)
    at MailParser._processStateHeader (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mailparser/lib/mailparser.js:357:18)
    at MailParser._process (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/node_modules/mailparser/lib/mailparser.js:227:22)
    at runCallback (timers.js:651:20)
```
Thanks, 
Vinh

**Comment by mscdex** [comment]
This is a `mailparser`/`iconv-lite` issue, not an `imap` issue. `iconv-lite` (which `mailparser` depends on), does not currently support any of the ISO-2022 encodings. FWIW you can voice your support for such encodings in [this `iconv-lite` issue](https://github.com/ashtuchkin/iconv-lite/issues/60).
