### ISSUE TITLE
Error: Mailbox doesn't exist: undefined

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#656]
Please help i got an error like bellow. What is wrong?

```
{ Error: Mailbox doesn't exist: undefined
    at Connection._resTagged (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Connection.js:1520:11)
    at Parser.<anonymous> (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Parser._resTagged (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:175:10)
    at Parser._parse (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:139:16)
    at Parser._tryread (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/Users/quangvinh/Projects/company/LeftCoastLogic/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
    at Socket.ondata (_stream_wrap.js:58:20) type: 'no', textCode: undefined, source: 'protocol' }
```

**Comment by mscdex** [comment]
Hard to tell without any code. Seems like you're passing the wrong mailbox value. Did you check the value you're passing to `openBox()`? Currently the value is not checked for truthy-ness and is blindly converted to string.

**Comment by quangvinh1305** [comment]
@mscdex 
```
	sendMessage: (req, res, next) => {
		var user = req.user, host;
		// TODO: return the sent message to the client
		let msg = req.body;
		let path = msg.path;
		req.imap.on('ready', () => {
			req.imap.openBox(path, (err, infoImap) => {
```

**Comment by mscdex** [comment]
Probably. Does `console.log(path === undefined)` print `true`?

**Comment by quangvinh1305** [comment]
Yes i checked. It is true.

**Comment by quangvinh1305** [comment]
@mscdex thanks.
