### ISSUE TITLE
How to calculate 25mb of a message?

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#673]
I want to compose an email has body, headers, inline attachments and attachments is limited 25MB.
How can i calculate correct the exactly email size?  Bellow is the error when i send an email with attachment 25mb.
[Refer for this issue](
https://support.isheriff.com/support/solutions/articles/195845-understanding-mail-attachments-)

```
{ Error: Message too large. https://support.google.com/mail/answer/6584#limit
    at Connection._resTagged (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Connection.js:1520:11)
    at Parser.<anonymous> (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Connection.js:194:10)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:189:7)
    at Parser._resTagged (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/lcl_dev/projects/companies/FlowOnlineProduct/DoMailServer/libs/imap/lib/Parser.js:53:12)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:186:7)
    at emitReadable_ (_stream_readable.js:432:10)
    at emitReadable (_stream_readable.js:426:7)
    at readableAddChunk (_stream_readable.js:187:13)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:551:20)
    at Socket.ondata (_stream_wrap.js:58:20) type: 'bad', textCode: 'TOOBIG', source: 'protocol' }

```

**Comment by mscdex** [comment]
Just check the byte length of the message data you're passing to `append()`?

**Comment by quangvinh1305** [comment]
@mscdex  
Your mean is check raw from mail composer. I'm trying to save it to sent folder use imap.

`								// build the rfc 822 message
								mailComposer.build((err, raw) => {
									if (err) return next(err);
									req.imap.append(raw, {
										mailbox: path,
										flags: ['\\Seen'],
										date: req.msg.date ? new Date(req.msg.date) : new Date()
									}, (err, uid) => {
										if (err) return next(err);

										msg.uid = uid;
										msg.path = path;
										msg.messageId = info.messageId;
										if (msg.from && !_.isArray(msg.from)) {
											msg.from = [{ address: msg.from }];
										}

										addMsgProps(msg, req.user);
										futil.json(req, res, {
											message: msg
										});
									});
								});`

**Comment by mscdex** [comment]
Yes, check `Buffer.byteLength(raw)`.
