### ISSUE TITLE
 Logging in is disabled on this server

### ISSUE THREAD

**Issue by Fantasy9527** [mscdex/node-imap#685]
```
[connection] Connected to host
<= '* OK The Microsoft Exchange IMAP4 service is ready.'
=> 'A0 CAPABILITY'
<= '* CAPABILITY IMAP4 IMAP4rev1 LOGINDISABLED STARTTLS UIDPLUS MOVE ID CHILDREN IDLE NAMESPACE LITERAL+'
<= 'A0 OK CAPABILITY completed.'
{ Error: Logging in is disabled on this server
    at Connection.<anonymous> (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Connection.js:1655:15)
    at Connection._resTagged (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Connection.js:194:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser._resTagged (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Parser.js:175:10)
    at Parser._parse (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Parser.js:139:16)
    at Parser._tryread (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Parser.js:82:15)
    at Socket.Parser._cbReadable (/Users/Fan/workspace/otrs-middleground/node_modules/_imap@0.8.19@imap/lib/Parser.js:53:12)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10) source: 'authentication' }
```

**Comment by mscdex** [comment]
You will need to either use the port for TLS instead *or* set the `autotls` option appropriately for the plaintext connection.
