### ISSUE TITLE
Fetching error on last message, but still msg ok

### ISSUE THREAD

**Issue by greenpdx** [mscdex/node-imap#709]
I fetch all messages when starting, before the last message I get this error. Every things work after that. Just give me an idea of where this error is and I will try to fix it.

FTCHERR { Error: The specified message set is invalid.
    at Connection._resTagged (/home/ubuntu/emailparse/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/home/ubuntu/emailparse/node_modules/imap/lib/Connection.js:194:10)
    at Parser.emit (events.js:182:13)
    at Parser._resTagged (/home/ubuntu/emailparse/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/home/ubuntu/emailparse/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/home/ubuntu/emailparse/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/home/ubuntu/emailparse/node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (events.js:182:13)
    at emitReadable_ (_stream_readable.js:531:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) type: 'no', textCode: undefined, source: 'protocol' }
MSGEND 175 39356 <9148c0d57976f527cb35f90bef771c60@www.versasafe.com> 
	 Sat, 23 Jun 2018 11:21:36 +0000 
	 VersaLink Notifications 
	 VersaLink <notifications@versasafe.com>
FTCHEND

**Comment by mscdex** [comment]
As the message says, there is something wrong with the first argument you're passing to `fetch()` that the server does not like.

**Comment by greenpdx** [comment]
thanx
