### ISSUE TITLE
Can't search message with UID search for yahoo.

### ISSUE THREAD

**Issue by quangvinh1305** [mscdex/node-imap#737]
Hi developers,
I have an errror when search an reply email with messageId from yahoo mail server like bellow. 
 

`
2018-11-19T04:02:28.460Z - info: <= 'A5 OK [READ-WRITE] SELECT completed; now in selected state'
2018-11-19T04:02:28.460Z - info: => 'A6 UID SEARCH OR (HEADER "IN-REPLY-TO" "1542598673985-6FD77F2B-397E1518-71D005B0") (HEADER "REFERENCES" "1542598673985-6FD77F2B-397E1518-71D005B0")'
2018-11-19T04:02:33.416Z - info: <= 'A6 NO [SERVERBUG] UID SEARCH Server error - Please try again later'
{ Error: UID SEARCH Server error - Please try again later
    at Connection._resTagged (libs/imap/lib/Connection.js:1520:11)
    at Parser.<anonymous> (libs/imap/lib/Connection.js:194:10)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser._resTagged (libs/imap/lib/Parser.js:175:10)
    at Parser._parse (libs/imap/lib/Parser.js:139:16)
    at Parser._tryread (libs/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (libs/imap/lib/Parser.js:53:12)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:601:20) type: 'no', textCode: 'SERVERBUG', source: 'protocol' }
2018-11-19T04:02:33.418Z - info: => 'A7 LOGOUT'

`

How can i search reply mail from yahoo mail server?

Thanks, 
Vinh

**Comment by mscdex** [comment]
As the error message indicates, it's a server error/bug/issue. You will need to contact Yahoo support about it.
