### ISSUE TITLE
How limit search results

### ISSUE THREAD

**Issue by Adibla** [mscdex/node-imap#749]
I tried to search all emails in my inbox but it fails probably because there are too messages to read (More than 4000), is there a way to limit my research?

**Comment by mscdex** [comment]
What exactly fails? Getting the search results or fetching the resulting messages?

**Comment by Adibla** [comment]
It doesn't return nothing from search.

**Comment by mscdex** [comment]
If you're not getting any errors and there are no search results, then that simply means the search criteria did not match any emails.

**Comment by Thomb89** [comment]
I have the same problem.
we got an test account with 3000+ unseen E-Mails and the search was stuck until i was at ~1400 E-Mails.
At that point i could log the following Error: 

```
ETCH parse error +43965ms
Error: FETCH parse error
    at Connection._resTagged (node_modules\imap\lib\Connection.js:1502:11)
    at Parser.<anonymous> (node_modules\imap\lib\Connection.js:194:10)
    at Parser.emit (events.js:210:5)
    at Parser._resTagged (node_modules\imap\lib\Parser.js:175:10)
    at Parser._parse (node_modules\imap\lib\Parser.js:139:16)
    at Parser._tryread (node_modules\imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (node_modules\imap\lib\Parser.js:53:12)
    at TLSSocket.emit (events.js:210:5)
    at emitReadable_ (_stream_readable.js:574:12)
    at processTicksAndRejections (internal/process/task_queues.js:79:21)
```

the Error persisted until i was at 1237 unseen mails. At that point imap could parse the result and i got 1237 messages.

**Comment by mscdex** [comment]
@Thomb89 Perhaps you're attempting to fetch more emails than the server is prepared to handle in a single fetch request?

**Comment by Thomb89** [comment]
The server was handling the request fine with the search method of [emailjs-imap-client](https://github.com/emailjs/emailjs-imap-client).
I'm currently in the process of migrating to node-imap due to the typescript support of node-imap.

**Comment by Thomb89** [comment]
That could be possible. 
Anyway - after getting a bit more familiar with your library, i found the function 'status' which also gets the count of unseen E-Mails.

Keep up the good work!
