### ISSUE TITLE
Error: Timed out while authenticating with server

### ISSUE THREAD

**Issue by huntsberg** [mscdex/node-imap#763]
I'm logged in but the lib doesn't know it, so it times out and throws and error.  I'm using typescript.  If I should be doing something differently, let me know.

imap.ts:
```
import Connection from "imap";
import { imapConfig } from "./imapConfig";

var rootCas = require('ssl-root-cas/latest').create();
require('https').globalAgent.options.ca = rootCas;

export class ImapServer {
    imapServer: Connection;

    constructor() {
        let configuration = new imapConfig();
        console.log('Connecting to %s', configuration.host);
        this.imapServer = new Connection({
            user: configuration.user,
            password: configuration.password,
            host: configuration.host,
            port: configuration.port,
            tls: configuration.tls,
            tlsOptions: { rejectUnauthorized: false },
            debug: console.log
        });
        this.imapServer.connect();
    }
    
}

```
imapConfig.ts
```
export class imapConfig {
    user: string = 'username';
    password: string = 'password';
    host: string = 'secure.emailsrvr.com';
    port: number = 993;
    tls: boolean = true;
}
```

main.ts
```
import { ImapServer } from "./Imap";

console.log("Starting Up");
let imapServer = new ImapServer().imapServer;
imapServer.connect();

imapServer.once('ready', function() {
    console.log("Server status: %s", imapServer.state);
    imapServer.openBox('INBOX', true, function(err, box){
        if (err) throw err;
        let f = imapServer.seq.fetch('1:1', {
            bodies: 'HEADER.FIELDS (FROM TO SUBJECT DATE)',
            struct: true
          });
        f.on('message', function(msg, seqno){
            console.log('Message #%d', seqno);
        });
    });
});
```
Here's the log:

> Starting Up
Connecting to secure.emailsrvr.com
[connection] Connected to host
<= '* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=TOKEN] Server ready proxy1.mail.ord1c.rsapps.net'
=> 'A0 CAPABILITY'
[connection] Connected to host
<= '* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=TOKEN] Server ready proxy1.mail.ord1c.rsapps.net'
<= '* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=TOKEN'
<= 'A0 OK Pre-login capabilities listed, post-login capabilities have more.'
=> 'A1 LOGIN "USERNAME" "PASSWORD"'
<= '* CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 XXXXXXXXX QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE QUOTA'
<= 'A1 OK Logged in'
=> 'A2 NAMESPACE'
<= '* NAMESPACE (("INBOX." ".")) NIL NIL'
<= 'A2 OK Namespace completed (0.000 + 0.000 secs).'
=> 'A3 LIST "" ""'
<= '* LIST (\\Noselect) "." ""'
<= 'A3 OK List completed (0.000 + 0.000 secs).'
Server status: authenticated
=> 'A4 EXAMINE "INBOX"'
<= '* FLAGS (\\Answered \\Flagged \\Deleted \\Seen \\Draft NonJunk Junk $Forwarded $Junk JunkRecorded $NotJunk Redirected unknown-1 unknown-4 unknown-0 NotJunk)'
<= '* OK [PERMANENTFLAGS ()] Read-only mailbox.'
<= '* 18789 EXISTS'
<= '* 0 RECENT'
<= '* OK [UNSEEN 2] First unseen.'
<= '* OK [UIDVALIDITY 1456786832] UIDs valid'
<= '* OK [UIDNEXT 167954] Predicted next UID'
<= '* OK [HIGHESTMODSEQ 391959] Highest'
<= 'A4 OK [READ-ONLY] Examine completed (0.000 + 0.000 secs).'
=> 'A5 FETCH 1:1 (UID FLAGS INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (FROM TO SUBJECT DATE)])'
<= '* 1 FETCH (UID 72634 FLAGS (\\Seen NonJunk) INTERNALDATE "05-Oct-2017 08:06:25 -0400" BODYSTRUCTURE (("text" "plain" ("charset" "utf-8" "format" "flowed") NIL NIL "8bit" 1464 66 NIL NIL NIL NIL)("text" "html" ("charset" "utf-8") NIL NIL "8bit" 3772 111 NIL NIL NIL NIL) "alternative" ("boundary" "------------7EACF69458DBA0CC5C4F4C45") NIL ("en-US") NIL) BODY[HEADER.FIELDS (FROM TO SUBJECT DATE)] {261}'
Message #1
<= '* 1 FETCH (UID 72634 FLAGS (\\Seen NonJunk) INTERNALDATE "05-Oct-2017 08:06:25 -0400" BODYSTRUCTURE (("text" "plain" ("charset" "utf-8" "format" "flowed") NIL NIL "8bit" 1464 66 NIL NIL NIL NIL)("text" "html" ("charset" "utf-8") NIL NIL "8bit" 3772 111 NIL NIL NIL NIL) "alternative" ("boundary" "------------7EACF69458DBA0CC5C4F4C45") NIL ("en-US") NIL) )'
<= 'A5 OK Fetch completed (0.218 + 0.000 + 0.217 secs).'
=> 'IDLE IDLE'
<= '+ idling'

> /scratch/hedwig/node_modules/imap/lib/Connection.js:139
      var err = new Error('Timed out while authenticating with server');
                ^
> Error: Timed out while authenticating with server
    at Timeout._onTimeout (/scratch/hedwig/node_modules/imap/lib/Connection.js:139:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by huntsberg** [comment]
I was connecting twice - I connected in main as well as the imap class.  The server recognized the double login and dropped the connection.

closing issue
