### ISSUE TITLE
Error: self signed certificate but only in Electron

### ISSUE THREAD

**Issue by Alt791350** [mscdex/node-imap#773]
Outside of electron it works fine but within electron I get this error.
```
[connection] Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
{ Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at clearBuffer (_stream_writable.js:545:7)
    at Socket.Writable.uncork (_stream_writable.js:319:7)
    at JSStreamSocket.doWrite (internal/js_stream_socket.js:161:17)
    at JSStream.onwrite (internal/js_stream_socket.js:19:57)
    at Socket.ondata (internal/js_stream_socket.js:63:22)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10) source: 'socket' }
[connection] Error: Error: self signed certificate
{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1257:34)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12)
    at Socket.ondata (internal/js_stream_socket.js:63:22)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }
[connection] Closed
```
I'm pretty sure my previous post got deleted without reason or a message why so that's a a-hole move whoever did that.

**Comment by mscdex** [comment]
Are you connecting a personal/non-public server? If so, that might explain the self-signed certificate. Otherwise, it means something/someone is MITM'ing your connection (security software has been known to do such things for example). As to why it's specifically happening to Electron, I don't know. Again, if it's security software to blame, it could be part of its detection algorithm.

> I'm pretty sure my previous post got deleted without reason or a message why so that's a a-hole move whoever did that.

Nobody deleted any of your posts in this repository. This is your first github issue here.

**Comment by Alt791350** [comment]
Seems to be a node 12 issue.
SNI isn't being send by default so you have to pass the `tlsOption` `serverName` with the host value to manually send the SNI and then that error won't appear.

Thanks anyway.

**Comment by broofa** [comment]
Looks like this is caused by a change in how Node handles TLS connections.  You now need to  See https://github.com/nodejs/node/issues/28167#issuecomment-500779815

I fixed this here by passing the server name as a `tlsOptions`.  E.g. Here's my config for connecting to GMail:
```
{
  user: 'my_user_name@gmail.com',
  password: '********',
  host: 'imap.gmail.com',
  port: 993,
  tls: true,
  tlsOptions: {
    servername: 'imap.gmail.com', // See https://github.com/nodejs/node/issues/28167
  },
}
```

@mscdex Consider reopening for the following enhancements?
- [ ] Add a note to docs about having to pass servername
- [ ] Default value of `config.tlsOptions.servername = config.host`
- [ ] Figure out how to make TLS error catchable
