### ISSUE TITLE
Urgent null check required.

### ISSUE THREAD

**Issue by shashankklenty** [mscdex/node-imap#783]
Hi I am currently encountering the error below in production. I believe just a null check needs to be added on the specific line, I would raise a PR but I don't want to mess with a code base I haven't ventured into.

Can someone please fixed this asap?

The error:
```
TypeError: Cannot read property 'toLowerCase' of null
at parseBodyStructure (/app/node_modules/imap/lib/Parser.js:496:24)
at parseBodyStructure (/app/node_modules/imap/lib/Parser.js:524:23)
at parseBodyStructure (/app/node_modules/imap/lib/Parser.js:472:18)
at parseBodyStructure (/app/node_modules/imap/lib/Parser.js:466:13)
at Parser.parseFetch (/app/node_modules/imap/lib/Parser.js:440:13)
at Parser._resUntagged (/app/node_modules/imap/lib/Parser.js:257:24)
at Parser._parse (/app/node_modules/imap/lib/Parser.js:137:16)
at Parser._tryread (/app/node_modules/imap/lib/Parser.js:82:15)
at Parser._parse (/app/node_modules/imap/lib/Parser.js:162:10)
at Parser._tryread (/app/node_modules/imap/lib/Parser.js:82:15)
at Parser._parse (/app/node_modules/imap/lib/Parser.js:162:10)
at Parser._tryread (/app/node_modules/imap/lib/Parser.js:82:15)
at TLSSocket.Parser._cbReadable (/app/node_modules/imap/lib/Parser.js:53:12)
at TLSSocket.emit (events.js:189:13)
at emitReadable_ (_stream_readable.js:535:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by lasdeparq** [comment]
Hi. The same error is happening to me.
Is there any provision for this to be fixed?
