### ISSUE TITLE
Cannot authenticate on hotmail

### ISSUE THREAD

**Issue by imsunburnt** [mscdex/node-imap#803]
I am getting a not authenticated error when I try to connect to Hotmail.  I am using the example given on the setup page.  Here is my info:

var imap = new Imap({
  user: 'myemail@hotmail.com',
  password: 'mypassword',
  host: 'outlook.office365.com',
  port: 993,
  tls: true
});

The host I took from Thunderbird account settings.  I am able to connect and receive email using Thunderbird and Win 10 Mail client.  I notice that the host I'm using is different than some others have used (in other issues): 'imap-mail.outlook.com', so I tried that one and got the not authenticated error too:

..Opening INBOX..
/home/pi/email-filter/node_modules/imap/lib/Connection.js:409
    throw new Error('Not authenticated');
    ^

Error: Not authenticated
    at Connection.openBox (/home/pi/email-filter/node_modules/imap/lib/Connection.js:409:11)
    at openInbox (/home/pi/email-filter/try.js:25:8)
    at Object.<anonymous> (/home/pi/email-filter/try.js:74:1)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11

Any suggestions for me?

**Comment by Sun-2** [comment]
Give us the full code.

Do you call `imap.connect()`?
