### ISSUE TITLE
TypeError: Cannot set property 'name' of undefined

### ISSUE THREAD

**Issue by chenlhlinux** [mscdex/node-imap#825]
```
node_modules/imap/lib/Connection.js:43
node[1065]:       self._box.name = name; 
node[1065]:                      ^       
node[1065]: TypeError: Cannot set property 'name' of undefined                                  
node[1065]:     at Connection.<anonymous> (/var/node/magic_screen/node_modules/imap/lib/Connection.js:431:22)  
node[1065]:     at Connection._resTagged (/var/node/magic_screen/node_modules/imap/lib/Connection.js:1535:22)  
node[1065]:     at Parser.<anonymous> (/var/node/magic_screen/node_modules/imap/lib/Connection.js:194:10)
node[1065]:     at Parser.emit (events.js:198:13)
node[1065]:     at Parser._resTagged (/var/node/magic_screen/node_modules/imap/lib/Parser.js:175:10)
node[1065]:     at Parser._parse (/var/node/magic_screen/node_modules/imap/lib/Parser.js:139:16)
node[1065]:     at Parser._tryread (/var/node/magic_screen/node_modules/imap/lib/Parser.js:82:15) 
node[1065]:     at TLSSocket.Parser._cbReadable (/var/node/magic_screen/node_modules/imap/lib/Parser.js:53:12)
node[1065]:     at TLSSocket.emit (events.js:198:13)  
node[1065]:     at emitReadable_ (_stream_readable.js:555:12)
```
I think shoud defend `self._box = {}` instand of `self._box = undefined`.

**Comment by chenlhlinux** [comment]
I have found the reason.
#546 
Thinks.
