### ISSUE TITLE
I get a error：Invalid credentials

### ISSUE THREAD

**Issue by AnsonCode** [mscdex/node-imap#826]
Error: Invalid credentials (Failure)
    at Connection._resTagged (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Connection.js:1502:11)
    at Parser.<anonymous> (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Connection.js:194:10)
    at Parser.emit (events.js:311:20)
    at Parser._resTagged (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Parser.js:175:10)
    at Parser._parse (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Parser.js:139:16)
    at Parser._tryread (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (D:\01-program\wechaty\node_modules\_imap@0.8.19@imap\lib\Parser.js:53:12)
    at TLSSocket.emit (events.js:311:20)
    at emitReadable_ (_stream_readable.js:562:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  type: 'no',
  textCode: 'AUTHENTICATIONFAILED',
  source: 'authentication'
}

**Comment by mscdex** [comment]
The error is pretty self-explanatory. The credentials you supplied were not accepted by the server.

**Comment by fanguangjian** [comment]
Change the email account access.
