### ISSUE TITLE
Error: Authentication Failed Icloud Imap

### ISSUE THREAD

**Issue by haardikg** [mscdex/node-imap#839]
ERROR BELOW

Error: Authentication Failed
    at Connection._resTagged (/Users/haardikgupta/node_modules/imap/lib/Connection.js:1502:11)
    at Parser.<anonymous> (/Users/haardikgupta/node_modules/imap/lib/Connection.js:194:10)
    at Parser.emit (events.js:315:20)
    at Parser._resTagged (/Users/haardikgupta/node_modules/imap/lib/Parser.js:175:10)
    at Parser._parse (/Users/haardikgupta/node_modules/imap/lib/Parser.js:139:16)
    at Parser._tryread (/Users/haardikgupta/node_modules/imap/lib/Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (/Users/haardikgupta/node_modules/imap/lib/Parser.js:53:12)
    at TLSSocket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
Emitted 'error' event on Connection instance at:
    at reentry (/Users/haardikgupta/node_modules/imap/lib/Connection.js:1610:12)
    at Connection.checkCaps (/Users/haardikgupta/node_modules/imap/lib/Connection.js:1635:22)
    at Connection._resTagged (/Users/haardikgupta/node_modules/imap/lib/Connection.js:1535:22)
    at Parser.<anonymous> (/Users/haardikgupta/node_modules/imap/lib/Connection.js:194:10)
    [... lines matching original stack trace ...]
    at TLSSocket.emit (events.js:315:20) {
  type: 'no',
  textCode: 'AUTHENTICATIONFAILED',
  source: 'authentication'
}

CODE BELOW

var Imap = require('imap'),
  inspect = require('util').inspect;

var imap = new Imap({
user: 'haardik21',
password: 'hARDU2005',
host: 'imap.mail.me.com',
port: 993,
tls: true,
tlsOptions: {
  rejectUnauthorized: false
}
});

imap.connect(function(err) {
  if(err)
  console.log(err)
})

**Comment by jpbecotte** [comment]
Have you created an app-specific password? https://support.apple.com/en-us/HT204397
