### ISSUE TITLE
append() breaks the connection if content is too long

### ISSUE THREAD

**Issue by xairoo** [mscdex/node-imap#868]
I store mails using `append()`. If the mail body (the message) is too long, the connection breaks, no idea why.
10824 bytes are the limit for the body (message), 10825 bytes will cause an error. Have tested it with removing characters in the middle of the body.

And I can increase the header for the same mail with content size 10824 bytes without problems. Looks like it's related to the body.

I am using [mimetext](https://github.com/muratgozel/MIMEText) to create the raw message, but that shouldn't be the problem. It's RFC-2822, but I have tested RFC-822 too, same problem.

```
<= '<body BAD Command Error. 10'
[connection] Ended
```

...

```
node_modules\imap\lib\Connection.js:1279
    if (!this._box && RE_OPENBOX.test(this._curReq.type))
                                                   ^

TypeError: Cannot read properties of undefined (reading 'type')
    at Connection._resUntagged (node_modules\imap\lib\Connection.js:1279:52)
    at Parser.<anonymous> (node_modules\imap\lib\Connection.js:191:10)
    at Parser.emit (node:events:520:28)
    at Parser._resUntagged (node_modules\imap\lib\Parser.js:271:10)
    at Parser._parse (node_modules\imap\lib\Parser.js:137:16)
    at Parser._tryread (node_modules\imap\lib\Parser.js:82:15)
    at TLSSocket.Parser._cbReadable (node_modules\imap\lib\Parser.js:53:12)
    at TLSSocket.emit (node:events:520:28)
    at emitReadable_ (node:internal/streams/readable:578:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by xairoo** [comment]
Moved to [MailComposer](https://nodemailer.com/extras/mailcomposer/), now the size doesn't matter ;-)
